# Generated by Django 5.2.1 on 2025-05-23 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarkdownFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='markdown_files/')),
                ('content', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_number', models.PositiveIntegerField()),
                ('chunk_type', models.CharField(choices=[('heading', 'Heading'), ('paragraph', 'Paragraph'), ('table', 'Table'), ('code', 'Code Block'), ('list', 'List'), ('image', 'Image')], max_length=20)),
                ('content', models.TextField()),
                ('headings', models.JSONField(blank=True, default=dict)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('markdown_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='api.markdownfile')),
            ],
            options={
                'ordering': ['chunk_number'],
                'unique_together': {('markdown_file', 'chunk_number')},
            },
        ),
    ]
