# Generated by Django 5.2.1 on 2025-05-23 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('anchor_text', models.CharField(blank=True, max_length=255)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chunk')),
                ('markdown_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.markdownfile')),
            ],
        ),
    ]
