# Generated by Django 5.2.1 on 2025-05-23 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markdownfile',
            name='content',
        ),
        migrations.RemoveField(
            model_name='markdownfile',
            name='title',
        ),
    ]
